name: m3e_widgets
description: "A single Flutter package providing Material 3 expressive components like material shapes, card list, dismissible cards, expandable cards and dropdown menu."
version: 0.1.5
homepage: https://github.com/Mudit200408/m3e_core
repository: https://github.com/Mudit200408/m3e_core
issue_tracker: https://github.com/Mudit200408/m3e_core/issues
publish_to: none

topics:
  - ui
  - material-3-expressive
  - dismissible
  - cards
  - dropdown

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.1.0
  path_drawing: ^1.0.1
  vector_math: ^2.2.0
  material_color_utilities: ^0.13.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/new_ink_sparkle.frag
  plugin:
    platforms:
      android:
        package: com.android.m3e_core
        pluginClass: M3eCorePlugin